version: '3'

services:
  member-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${DB_DATABASE:-member_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DB_PASSWORD:-postgres}"
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    networks:
      - member-net

  member-svc:
    build: .
    restart: always
    environment:
      DB_DRIVER: 'postgres'
      DB_HOST: ${DB_HOST:-member-db}
      DB_DATABASE: ${DB_DATABASE:-member_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-secret}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME:-1d}
      JWT_ISS: eJKgSgQnqnXYXqF8Wl81blzrV2CLhFLs
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://localhost:5672}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - member-db
    networks:
      - api-gateway_kong-net
      - member-net
      - rabbit-mq_rabbitmq-net
    ports:
      - "8888:3000"

networks:
  api-gateway_kong-net:
    external: true
  member-net:
    external: false
  rabbit-mq_rabbitmq-net:
    external:
      true
