version: '3'

services:
  frontend-svc:
    build: .
    restart: always
    environment:
      JWT_SECRET_KEY: secret
      JWT_EXPIRATION_TIME: '1d'
      JWT_ISS: eJKgSgQnqnXYXqF8Wl81blzrV2CLhFLs
      NEXT_PUBLIC_BACKEND_URL: http://everything101.xyz:8000/v1
      NEXTAUTH_URL: http://everything101.xyz
      NODE_ENV: 'development'
    ports:
      - "80:3000"
