_format_version: "3.0"
consumers:
- jwt_secrets:
  - algorithm: HS256
    key: eJKgSgQnqnXYXqF8Wl81blzrV2CLhFLs
    secret: secret
  username: bistro
plugins:
- config:
    credentials: false
    exposed_headers: null
    headers: null
    max_age: null
    methods:
    - GET
    - HEAD
    - PUT
    - PATCH
    - POST
    - DELETE
    - OPTIONS
    - TRACE
    - CONNECT
    origins: null
    preflight_continue: false
  enabled: true
  name: cors
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: member-svc
  name: auth-service
  path: /auth
  port: 3000
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: e66f2250-cc64-4640-b7de-242967f509a1
    methods:
    - POST
    - OPTIONS
    path_handling: v1
    paths:
    - /v1/auth-service
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: bistro-svc
  name: bistro-service
  port: 3000
  protocol: grpc
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: e83a2db1-6819-4db5-a157-9a367dd962b6
    path_handling: v1
    paths:
    - /v1/bistro-service
    plugins:
    - config:
        proto: /opt/kong/protobuf/bistro.proto
      enabled: true
      name: grpc-gateway
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: member-svc
  name: member-service
  path: /user
  plugins:
  - config:
      anonymous: null
      claims_to_verify: null
      cookie_names: []
      header_names:
      - authorization
      key_claim_name: iss
      maximum_expiration: 0
      run_on_preflight: true
      secret_is_base64: false
      uri_param_names:
      - jwt
    enabled: true
    name: jwt
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 3000
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: 7befc40c-11cd-43b1-93d0-e085f2b9d003
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    path_handling: v1
    paths:
    - /v1/member-service
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: menu-svc
  name: menu-service
  port: 3000
  protocol: grpc
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: 29a0be78-40c9-4e35-b65d-aa84bbceef71
    path_handling: v1
    paths:
    - /v1/menu-service
    plugins:
    - config:
        proto: /opt/kong/protobuf/menu.proto
      enabled: true
      name: grpc-gateway
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: order-svc
  name: order-service
  port: 3000
  protocol: grpc
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: 27bea29e-1488-4f6e-842c-37b219af076a
    path_handling: v1
    paths:
    - /v1/order-service
    plugins:
    - config:
        proto: /opt/kong/protobuf/order.proto
      enabled: true
      name: grpc-gateway
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: qrcode-svc
  name: qrcode-service
  port: 3000
  protocol: grpc
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: b5e292b8-1eeb-4cde-a842-3cb24e667b8c
    path_handling: v1
    paths:
    - /v1/qrcode-service
    plugins:
    - config:
        proto: /opt/kong/protobuf/qrcode.proto
      enabled: true
      name: grpc-gateway
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
certificates:
- cert: "-----BEGIN CERTIFICATE-----
    MIICVDCCAb2gAwIBAgIBADANBgkqhkiG9w0BAQ0FADBHMQswCQYDVQQGEwJ0aDEQ
    MA4GA1UECAwHQkFOR0tPSzENMAsGA1UECgwEVEVTVDEXMBUGA1UEAwwOMTc4LjEy
    OC4yNi4yNTMwHhcNMjIxMTI1MDE1NzE2WhcNMjMxMTI1MDE1NzE2WjBHMQswCQYD
    VQQGEwJ0aDEQMA4GA1UECAwHQkFOR0tPSzENMAsGA1UECgwEVEVTVDEXMBUGA1UE
    AwwOMTc4LjEyOC4yNi4yNTMwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMWf
    WbuAIQ/zkqOleWpcY0No3EL3KA6yQebiUZPx3yEFX7XQAzCHl+Mpz288QwuIQWBs
    7l89iujQ3mtepQADq/JWausoWlbO5sNmMCpxEeVurKCJiLuminZr/8Jd83vygK54
    pjx+CkR2FRAZFI7W6dKcuR7heFYhHzdgd7gKPkfpAgMBAAGjUDBOMB0GA1UdDgQW
    BBS4v9AjywWGui69nNWQ9A2EBHOmzTAfBgNVHSMEGDAWgBS4v9AjywWGui69nNWQ
    9A2EBHOmzTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBDQUAA4GBACBcxpRLmj59
    jqJNv177C3LjQ9Ga21Y2FToWZYYhiAbUPFyxbb1roYvAZzv5D/qerKsL9ldhEScZ
    0Kc5kPDXYyfuxMc+qI4VSN2m5LFsCSnNJLhN2DTelcKD9ned0izqRQRb2tUKaKNl
    Enoocw4gOoksNIF8jNfY0hvavBqt/nG0
    -----END CERTIFICATE-----"
  key: "-----BEGIN PRIVATE KEY-----
    MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAMWfWbuAIQ/zkqOl
    eWpcY0No3EL3KA6yQebiUZPx3yEFX7XQAzCHl+Mpz288QwuIQWBs7l89iujQ3mte
    pQADq/JWausoWlbO5sNmMCpxEeVurKCJiLuminZr/8Jd83vygK54pjx+CkR2FRAZ
    FI7W6dKcuR7heFYhHzdgd7gKPkfpAgMBAAECgYANZozTJhEX39BlwGbHS5R/kbC9
    6byRoozNdzNI8PHMb2zaC0zsEYW/JaqnRFLXiVnFjB1t3+J3fxJV/Yj6w0T5fzrx
    by5QM2bNkNonEhaEkmfjGzQ9fnai5S9v5XA8HyCf/xrkpo600Tg2dP/8R/3yHKax
    zxaFaTl286i6fas2AQJBAPW8Y8BSdV5ZsC7lLK+pM0S7TAuI2pxshUu1cpj1ZfRv
    pd5i9s50TSP4KSo3maT9B7p7X0KJz33m2f1nZUqIWrkCQQDN4H4RLQOshLle8SF1
    DCShgXzeWqAiiMepBvc8kxRqjYM0BNd1yWLuvcGI4BwjR7A8SkeyuqbpVWNQL/9t
    lP6xAkB8nQYwtyARsoWnokvg4HrBNgHAL6w8esO1utPcQUVsiVmhxqnF1DByNxwY
    7o0Zn77VkE6kXWI9RF3zJQW2oCLxAkBOQHvqb1+sHS6QRbrf0GPD94HMykl/ltm9
    B2bF4WmrLmqmRQjYPlmaQQnkyronNsJnyBwEdSmoGsqK2hOORUmhAkBOP5YvP1T7
    MlM0ypDbQmauCIYoJ4vxsF2R+Ijqg+04Yqh43ZPiHJo05hyACaVDx4pL6S1Bs2uZ
    umQJvezIsBdO
    -----END PRIVATE KEY-----"
  snis:
  - name: everything101.xyz