version: '3'

services:
  menu-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${DB_DATABASE:-menu_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_PASSWORD:-postgres}" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    networks:
      - menu-net

  menu-svc:
    build: .
    restart: always
    environment:
      DB_DRIVER: 'postgres'
      DB_HOST: ${DB_HOST:-menu-db}
      DB_DATABASE: ${DB_DATABASE:-menu_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - menu-db
    networks:
      - api-gateway_kong-net
      - menu-net

networks:
  api-gateway_kong-net:
    external: true
  menu-net:
    external: false
