version: '3'

services:
  notification-svc:
    build: .
    restart: always
    environment:
      DB_URL: ${DB_URL:-mongodb://localhost:27017/notification}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://localhost:5672}
      SMTP_USER: ${SMTP_USER:-user@localhost.local}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-password}
      NODE_ENV: 'development'
    networks:
      - notification-net
      - rabbit-mq_rabbitmq-net

networks:
  notification-net:
    driver: bridge
  rabbit-mq_rabbitmq-net:
    external:
      true
