version: "3.9"

services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: bistro-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-Password123}
    restart: always
    ports:
      - 15672:15672
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge