version: '3'

services:
  bistro-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${PG_DATABASE:-bistro_db}
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_PASSWORD:-postgres}" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    networks:
      - bistro-net

  bistro-svc:
    build: .
    restart: always
    environment:
      DB_DRIVER: 'postgres'
      DB_HOST: bistro-db
      DB_DATABASE: ${PG_DATABASE:-bistro_db}
      DB_USER: ${PG_USER:-postgres}
      DB_PASSWORD: ${PG_PASSWORD:-postgres}
      DB_PORT: 5432
      NODE_ENV: 'development'
    depends_on:
      - bistro-db
    networks:
      - api-gateway_kong-net
      - bistro-net

networks:
  api-gateway_kong-net:
    external: true
  bistro-net:
    external: false
